### ISSUE TITLE
Placeholders aren't working

### ISSUE THREAD

**Issue by Stephanech** [pixar02/InfoboardReloaded#10]
I just installed the plugin and PlaceholderAPI, both of them enabled succesfully but in the scoreboard it seems not to be working

"Welcome!
%player_name%

Health:
%player_health%/%player_max_health%"

I'm running Spigot 1.12 in a localhost offline testing server, maybe that is the issue?

**Comment by pixar02** [comment]
Install the Player expansion from PlaceholderAPI. you can do it with the command: "/papi ecloud download player" or you can download it directely from there wiki page: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
