### ISSUE TITLE
How to make the scoreboard show if there is a condition

### ISSUE THREAD

**Issue by BoomEaro** [pixar02/InfoboardReloaded#11]
For example, I want the scoreboard 1 to be displayed if the player is in the clan of simpleclans, placeholderapi has a variable %simpleclans_in_clan%
If it equals true, then the panel will appear, if false, it will be hidden.
Is it possible to do this? If not, can you add this feature?

**Comment by pixar02** [comment]
Yea, I think that it would be possible. 
I will take some time since it's an entire new feature.

**Comment by pixar02** [comment]
This Issue tread will be closing! Pls repost you issue on the new issue page: https://github.com/Ktar5/Info-Board/issues
