### ISSUE TITLE
mcMMO Combat Level

### ISSUE THREAD

**Issue by madtomic** [pixar02/InfoboardReloaded#2]
Can you please add support for variable for combat level from this plugin?

https://dev.bukkit.org/projects/mccombatlevel

Thank you

**Comment by pixar02** [comment]
What would you like to see? (placeholders)
%....%

**Comment by pixar02** [comment]
Done!
source code: 
https://github.com/pixar02/McCombatLevel-Expansion 
Download page:
https://www.spigotmc.org/resources/mccombatlevel-expansion.47040/
All instructions are on the download page!
