### ISSUE TITLE
PlaceholderAPI-2.8.2

### ISSUE THREAD

**Issue by madtomic** [pixar02/InfoboardReloaded#4]
I am using this version and console is spamming this...

[01:58:35] [Server thread/ERROR]: [MVdWPlaceholderAPI] Unable to replace placeholders. No MVdW Placeholder plugin found!

Any idea if this is supported in the latest IBR?

**Comment by madtomic** [comment]
This is spigot 1.12.1 and latest version of IBR.

**Comment by pixar02** [comment]
If you want to use MVdW placeHolders you need one of his plugins....
I don't knw why he made it like that but it won't work...

**Comment by madtomic** [comment]
Thank you,
