### ISSUE TITLE
Using  ProtocolLib to enable compatibilityMode for IBR

### ISSUE THREAD

**Issue by madtomic** [pixar02/InfoboardReloaded#5]
![image](https://user-images.githubusercontent.com/6004542/30342949-a380c5da-97c9-11e7-82d2-6ab176a472db.png)

Can you please add a compatibilityMode in the configuration and by using ProtocolLib to enable IBR scoreboard to be show along with combat level to show over playerhead.

If you need some ideas, please see scoreboardstats.
https://dev.bukkit.org/projects/scoreboardstats
github: https://github.com/games647/ScoreboardStats

ProtocolLib: https://www.spigotmc.org/resources/protocollib.1997/

As of now, the scoreboard is not allowing the tag to be show over playerhead.

**Comment by pixar02** [comment]
I will Look in to it!
Thanks for pointing this out for me!

**Comment by madtomic** [comment]
There also new scoreboard API in the new bukkit. Maybe look there as well.

**Comment by pixar02** [comment]
Ok, thanks!

**Comment by pixar02** [comment]
This Issue tread will be closing! pls repost you issue on the new issue page: https://github.com/Ktar5/Info-Board/issues
