### ISSUE TITLE
PermissionsEx (PEX)

### ISSUE THREAD

**Issue by madtomic** [pixar02/InfoboardReloaded#6]
Can you please add support for variables from  PermissionsEx (PEX)?

https://dev.bukkit.org/projects/permissionsex

some variables examples:

%prefix%
Vault permission group prefix
%userprefix%
Vault permission user prefix
%suffix%
Vault permission group suffix
%usersuffix%
Vault permission user suffix
%group%
Vault permission group
%prefix_group_2%
Vault permission group prefix {prefix_group_2}
%suffix_group_2%
Vault permission group suffix {prefix_group_2}

Thanks!

**Comment by pixar02** [comment]
Will also look in to it! 
On a side note Pex hooks in to Vault and since there is an expansion for Vault maybe you should try that ?

**Comment by madtomic** [comment]
I tried and it don't seems to have what I am looking for.

**Comment by madtomic** [comment]
Expansion for Vault? Could you link it here.

**Comment by pixar02** [comment]
Vault has an expansion. There is no download link. If you want that expansion: do this in your console: "/papi ecloud list all" as far as I remeber there are 80 expansions in the ecloud. 

I will see if the PEX expansion is possible, I'm pretty busy at the moment with some personal stuff, but will work on it when I have the time.

**Comment by madtomic** [comment]
Ok, thank you. I did try Valut and it seems PowerRanks have what I need so if you could add variables from PEX. I expect it to work about the same. Thank you again.

**Comment by pixar02** [comment]
I looked into making an expansion for PEX. it is possible for the prefix and suffix but getting the group,.... It would become extremly complex. So I would suggest using the Vault expansion, since it hooks into PEX, you would be able to get the prefix,suffix,group,next group,... all though Vault's expansion...
This all the placeholders Vault has for persmissions:
```%vault_rank%
%vault_prefix%
%vault_rankprefix%
%vault_rankprefix_#%
%vault_suffix%
%vault_ranksuffix%
%vault_ranksuffix_#%
%vault_prefix_color%```
