### ISSUE TITLE
Variable and PerWorldScore Request

### ISSUE THREAD

**Issue by SpringTraps152** [pixar02/InfoboardReloaded#8]
![screenshot_4](https://user-images.githubusercontent.com/33912376/33152286-ac60e8b4-cfba-11e7-9352-e0b9277f3bf8.png)
- can you add some things in a next version or a expansion?
https://goo.gl/D1dbz4

variable suggested for the plugin:
map: %map% - name of the map
money earned: &earn% - money gained for killed a player and/or win a game
killed: %kills% - player killed other player
remaining: %remain% - others players online in the actual map

per world/map scoreboard
option suggested:
PerScoreWorld: <true/false>
1=global
2=test
3=anotherTest

![screenshot_6](https://user-images.githubusercontent.com/33912376/33153771-90d0cb52-cfc2-11e7-86ac-18a4b9590848.png)

**Comment by pixar02** [comment]
I will look into creating a expansion. But I don't understand what you mean with:
> per world/map scoreboard
option suggested:
PerScoreWorld: <true/false>
1=global
2=test
3=anotherTest

Is that a sugestion for the expansion or the plugin?

**Comment by SpringTraps152** [comment]
Yes, expansion, it's for multi-view on different worlds

**Comment by pixar02** [comment]
I'm already working on a better way for the per World scoreboards displays.
But I will keep this in mind! (Give me some time for the expansion, personal stuff is getting in the way of working on the plugin.)

**Comment by SpringTraps152** [comment]
uhh, can you tell me if you have some free time? (if you do not want do not need to tell)

**Comment by pixar02** [comment]
This Issue tread will be closing! Pls repost you issue on the new issue page: https://github.com/Ktar5/Info-Board/issues
